print("archivo ")
print("archivo modificado desde feature/modificacion")
print("archivo A MODIFICADO DESDE feature/mergeo")
print("nueva modificacion archivo A MODIFICADO DESDE feature/mergeo")
print("realizando una nueva modificacion en el archivo A sobre squash")